pro_tips/apps/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout, password_reset, password_reset_confirm, password_reset_done, password_change, password_reset_complete

urlpatterns = patterns('pro_tips.apps.accounts.views',
        ##PROFILE URLS
        url(r'^profile/$','user_profile',name='user-profile'),

        ## AUTH URLS
       url(r'^register/$', 'registration', name='register'),

       url(r'^login/$', login, {
            'template_name': 'user_profiles/sites/login.html'
        }, name='login'),

       url(r'^logout/$', logout, {
           'next_page': '/'
       }, name='logout'),

       url(r'^reset/$', password_reset, {
           #'template_name': 'profiles/sites/reset_password.html',
           'email_template_name': 'user_profiles/emails/reset_password.html',
           'post_reset_redirect': '/user-profiles/logout/'}, name='reset'),

       url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            password_reset_confirm,{
               'post_reset_redirect': '/user-profiles/login'
           },
            name='password_reset_confirm'),
       url(r'^reset/complete/$', password_reset_complete, {
           #'template_name': 'profiles/sites/reset_password.html',
            }, name='password_reset_complete'),

       url(r'^reset-done/?$', password_reset_done,name='password_reset_done'),

       url(r'^password_change/$', password_change, {
           'template_name': 'profiles/sites/change_password.html',
           'post_change_redirect': '/panel/logout/'},name='pwd-change'),


)

pro_tips/apps/sites/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout, password_reset, password_reset_confirm, password_reset_done, password_change, password_reset_complete

urlpatterns = patterns('pro_tips.apps.sites.views',

        url(r'^$', 'index', name='index'),

)

pro_tips/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('pro_tips.apps.main_sites.urls') , name='home'),

    url(r'^accounts/', include('pro_tips.apps.accounts.urls', namespace="accounts")),
    url(r'^api/', include('pro_tips.apps.api.urls', namespace="api")),

    #include django-admin urls
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    (r'^comments/', include('django.contrib.comments.urls')),


    #Third-party apps urls
    url(r'', include('social_auth.urls')),
    url(r'^front-edit/', include('front.urls')),
)

from django.conf import settings
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

pro_tips/apps/accounts/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.conf import settings

LANGUAGES = settings.LANGUAGES

class CUser(AbstractUser):
    pass

class CUserProfile(models.Model):
    user = models.ForeignKey('CUser',verbose_name=_("User"))
    language = models.CharField(_("Language"), max_length=2, choices=LANGUAGES)

    def __unicode__(self):
        return u"%s (%s)" %(self.user, self.language)

pro_tips/apps/accounts/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CUser


class CUserCreationForm(UserCreationForm):
    class Meta:
        model = CUser
        fields = ['username', 'email', ]

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            CUser._default_manager.get(username=username)
        except CUser.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

pro_tips/apps/accounts/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.messages.api import get_messages
from django.template.response import TemplateResponse


from pro_tips.apps.accounts.forms import CUserCreationForm
from django.contrib.auth import authenticate, login


###PROFILE
from pro_tips.apps.tips.models import Favourite

@login_required
def user_profile(request):
    favs = Favourite.objects.filter(user=request.user)
    context = {
        'favs': favs,
        'favs_count': favs.count(),
        'alert_count': 0
    }
    return TemplateResponse(request, 'user_profiles/sites/user_profile.html',context)



##AUTH
def registration(request):
    context = {}

    registration_form = CUserCreationForm(request.POST or None)
    if registration_form.is_valid():
        user = registration_form.save()
        log_in_user = authenticate(username=user.username,
                                    password=request.POST['password2'])
        login(request,log_in_user)
        return redirect("accounts:user-profile")
    context.update({
        'form': registration_form,
    })
    return TemplateResponse(request, 'user_profiles/sites/registration.html', context)

pro_tips/apps/accounts/templates/user_profiles/sites/login.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="col-md-6 col-md-offset-3">
    <span class="login"><strong>{% trans 'Log in form' %}</strong></span>
    <br/><br/>

    <form action="#" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="/"/>

        <div class="form-group">
            <div class="">
                <input class="form-control" id="id_username" name="username"
                       type="text"
                       placeholder="Login">
            </div>
        </div>
        <div class="form-group">
            <div class="">
                <input class="form-control" maxlength="30" name="password"
                       type="password"
                       placeholder="{% trans 'Password' %}">
            </div>
        </div>
        {% if form.errors %}
            <div class="col-sm-12">
                <span class="error span">{% trans "Invalid username or password." %} <br/><br/></span>
            </div>
        {% endif %}
        <div class="col-lg-8">
            <span class="reminder"><a
                    href="{% url 'accounts:reset' %}">{% trans "Forgot password" %}</a> <br/></span>
            <span class="reminder"><a
                    href="{% url 'accounts:register' %}">{% trans "Don't have account?" %}</a></span>
        </div>
        <div class="col-lg-3 pull-right">
            <input type="submit"
                    class="btn btn-danger" value="{% trans "Log in" %}"/>
        </div>

    </form>
    </div>
{% endblock %}

pro_tips/apps/accounts/templates/user_profiles/sites/registration.html
{% extends "base.html" %}
{% load i18n bootstrap %}


{% block content %}

        <div id="content-registration">
            <div class="col-sm-8 col-sm-offset-2">
                <span class="login"><strong>Rejestracja</strong></span>
                <br/><br/>
                <form action="#" method="POST">
                    {% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit" class="btn btn-default">Zarejestruj się</button>
                </form>
            </div>
        </div>
    <hr/>
{% endblock %}

pro_tips/apps/accounts/templates/user_profiles/sites/user_profile.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}

<section id="profile">
        <h2 class="section-title">{% trans "User profile" %} {{ request.user }}</h2>

        <div class="row">
            <div class="col-md-4">
                <ul class="nav nav-pills nav-stacked news-list">
                    <li class="active">
                        <a href="#news1" data-toggle="tab" class="">
                            <i class="fa fa-gamepad"></i> {% trans "Favs" %} <div class="badge badge-info pull-right">{{ favs_count }}</div>
                        </a>
                    </li>
                    <li>
                        <a href="#news2" data-toggle="tab" class="">
                            <i class="fa fa-gears"></i> {% trans "Settings" %}
                        </a>
                    </li>
                    <li>
                        <a href="#news3" data-toggle="tab" class="">
                            <i class="fa fa-list-alt"></i> {% trans "Alerts" %} <div class="badge badge-info pull-right">{{ alert_count }}</div>
                        </a>
                    </li>
                    <li>
                        <a href="#news4" data-toggle="tab" class="">
                            <i class="fa fa-star"></i> {% trans "Fallowers" %}
                        </a>
                    </li>

                </ul>
                <!-- list-group -->
            </div>
            <div class="col-md-8">
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="news1">
                        <article class="news-content">
                            <h3 class="news-content-title"><i class="fa fa-gamepad"></i> {% trans "Favourites" %}</h3>
                            <hr/>
                            {% for fav in favs %}
                                <div class="media">
                                  <a class="pull-left" href="#">
                                    <img class="media-object" alt="64x64" src="{{ fav.tip.language.img.url }}" style="width: 64px; height: 64px;">
                                  </a>
                                  <div class="media-body">
                                    <h4 class="media-heading">{{ fav.tip.title }}</h4>
                                    {{ fav.tip.description|truncatewords:20 }}
                                  </div>
                                </div>
                                <hr/>
                            {% endfor %}
                        </article>
                    </div>
                    <div class="tab-pane fade" id="news2">
                        <article class="news-content">
                            <h3 class="news-content-title"><i class="fa fa-gears"></i> {% trans "Settings" %}</h3>


                            <p>Aliquip pariatur esse Excepteur enim Duis in ex dolor amet aute mollit officia aliqua
                                dolor laboris consequat incididunt sit cillum veniam Excepteur esse laborum exercitation
                                mollit commodo sunt. Lorem ipsum Enim anim mollit sed. Lorem ipsum Ea in in occaecat
                                sunt laboris. Lorem ipsum Tempor enim dolor ut culpa aliquip.</p>

                            <p>Ullamco deserunt cupidatat ut ut velit laboris. physico faciunt. Dicere loquuntur
                                consequentis artibus afranius, rudem remotis pericula cumque, nescio causam repellendus,
                                amotio derepta laborum occultarum.</p>

                            <p>Lorem ipsum Mollit Ut dolor adipisicing pariatur sed esse sit elit non dolor. Lorem ipsum
                                Commodo commodo Ut reprehenderit do cillum incididunt elit pariatur velit commodo. Lorem
                                ipsum Consequat est Duis culpa sed.</p>
                        </article>
                    </div>
                    <div class="tab-pane fade" id="news3">
                        <article class="news-content">
                            <h3 class="news-content-title"><i class="fa fa-list-alt"></i> {% trans "Alerts" %}</h3>


                            <p>Aliquip pariatur esse Excepteur enim Duis in ex dolor amet aute mollit officia aliqua
                                dolor laboris consequat incididunt sit cillum veniam Excepteur esse laborum exercitation
                                mollit commodo sunt. Lorem ipsum Enim anim mollit sed. Lorem ipsum Ea in in occaecat
                                sunt laboris. Lorem ipsum Tempor enim dolor ut culpa aliquip.</p>

                            <p>Ullamco deserunt cupidatat ut ut velit laboris. physico faciunt. Dicere loquuntur
                                consequentis artibus afranius, rudem remotis pericula cumque, nescio causam repellendus,
                                amotio derepta laborum occultarum.</p>

                            <p>Lorem ipsum Mollit Ut dolor adipisicing pariatur sed esse sit elit non dolor. Lorem ipsum
                                Commodo commodo Ut reprehenderit do cillum incididunt elit pariatur velit commodo. Lorem
                                ipsum Consequat est Duis culpa sed.</p>
                        </article>
                    </div>
                    <div class="tab-pane fade" id="news4">
                        <article class="news-content">
                            <h3 class="news-content-title"><i class="fa fa-star"></i> {% trans "Fallowers" %}</h3>


                            <p>Aliquip pariatur esse Excepteur enim Duis in ex dolor amet aute mollit officia aliqua
                                dolor laboris consequat incididunt sit cillum veniam Excepteur esse laborum exercitation
                                mollit commodo sunt. Lorem ipsum Enim anim mollit sed. Lorem ipsum Ea in in occaecat
                                sunt laboris. Lorem ipsum Tempor enim dolor ut culpa aliquip.</p>

                            <p>Ullamco deserunt cupidatat ut ut velit laboris. physico faciunt. Dicere loquuntur
                                consequentis artibus afranius, rudem remotis pericula cumque, nescio causam repellendus,
                                amotio derepta laborum occultarum.</p>

                            <p>Lorem ipsum Mollit Ut dolor adipisicing pariatur sed esse sit elit non dolor. Lorem ipsum
                                Commodo commodo Ut reprehenderit do cillum incididunt elit pariatur velit commodo. Lorem
                                ipsum Consequat est Duis culpa sed.</p>
                        </article>
                    </div>

                    </div>
                </div>
                <!-- tab-content -->
            </div>
        </div>
    </section> <!-- news -->

{% endblock %}