pro_tips/apps/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout, password_reset, password_reset_confirm, password_reset_done, password_change, password_reset_complete

urlpatterns = patterns('pro_tips.apps.accounts.views',
        ##PROFILE URLS
        url(r'^profile/$','user_profile',name='user-profile'),

        ## AUTH URLS
       url(r'^register/$', 'registration', name='register'),

       url(r'^login/$', login, {
            'template_name': 'user_profiles/sites/login.html'
        }, name='login'),

       url(r'^logout/$', logout, {
           'next_page': '/'
       }, name='logout'),

       url(r'^reset/$', password_reset, {
           #'template_name': 'profiles/sites/reset_password.html',
           'email_template_name': 'user_profiles/emails/reset_password.html',
           'post_reset_redirect': '/user-profiles/logout/'}, name='reset'),

       url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            password_reset_confirm,{
               'post_reset_redirect': '/user-profiles/login'
           },
            name='password_reset_confirm'),
       url(r'^reset/complete/$', password_reset_complete, {
           #'template_name': 'profiles/sites/reset_password.html',
            }, name='password_reset_complete'),

       url(r'^reset-done/?$', password_reset_done,name='password_reset_done'),

       url(r'^password_change/$', password_change, {
           'template_name': 'profiles/sites/change_password.html',
           'post_change_redirect': '/panel/logout/'},name='pwd-change'),


)

pro_tips/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('pro_tips.apps.main_sites.urls') , name='home'),

    url(r'^accounts/', include('pro_tips.apps.accounts.urls', namespace="accounts")),
    url(r'^api/', include('pro_tips.apps.api.urls', namespace="api")),

    #include django-admin urls
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    (r'^comments/', include('django.contrib.comments.urls')),


    #Third-party apps urls
    url(r'', include('social_auth.urls')),
    url(r'^front-edit/', include('front.urls')),
)

from django.conf import settings
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

pro_tips/templates/includes/menu/menu.html
{% load i18n %}
<!-- Fixed navbar -->
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><span class="badge"><i class="fa fa-code"></i> {% trans "Pro tips" %}</span></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% if not request.user.is_authenticated %}
                <li><a href="{% url "accounts:login" %}"><i class="fa fa-user"></i> {% trans "Log in" %}</a></li>
                <li><a href="{% url "accounts:register" %}"><i class="fa fa-sign-in"></i> {% trans "Register" %}</a></li>
                <li><a href="{% url "socialauth_begin" "facebook" %}"><i class="fa fa-facebook"></i> {% trans "Sign in by FB" %}</a></li>
                <!--<li><a href="{% url "socialauth_begin" "github" %}"><i class="fa fa-github"></i> {% trans "Sign in by GitHub" %}</a></li>-->
                <li><a href="{% url "socialauth_begin" "google-oauth2" %}"><i class="fa fa-google-plus"></i> {% trans "Sign in by Google" %}</a></li>
            {% else %}
                <li><a href="{% url "accounts:user-profile" %}"><i class="fa fa-user"></i> {% trans "User profile" %}</a></li>

            {% endif %}
          </ul>
          {% if request.user.is_staff %}
              <ul class="nav navbar-nav pull-right">
                    <li><a href="{% url "admin:index" %}"><i class="glyphicon glyphicon-globe"></i> {% trans "Admin" %}</a></li>
                    <li><a href="{% url "accounts:logout" %}"><i class="glyphicon glyphicon-log-out"></i> {% trans "Logout" %}</a></li>
              </ul>
           {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </div>